#!/usr/bin/env bash

if [ -z $1 ]; then
    echo "Please provide a user name"
fi

echo "Please enter root password"
su root -c "apt-get install sudo; adduser $1 sudo; adduser $1 staff"
echo "Please log out and back in for changes to take effect"
echo
